In [1]:
import pandas as pd
 

# ===========================================================
# PANDAS LEVEL 1 - BASICS
# ===========================================================

# -----------------------------------------------------------
# 1. Create DataFrame from Dictionary
# -----------------------------------------------------------

data = {
    "EmpID": [101, 102, 103, 104, 105],
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Age": [25, 30, 35, 28, 26],
    "Department": ["HR", "IT", "Finance", "IT", "HR"],
    "Salary": [50000, 70000, 80000, 65000, 55000],
    "City": ["Pune", "Mumbai", "Delhi", "Bangalore", "Pune"]
}

 

df =pd.DataFrame(data)
df

   EmpID     Name  Age Department  Salary       City
0    101    Alice   25         HR   50000       Pune
1    102      Bob   30         IT   70000     Mumbai
2    103  Charlie   35    Finance   80000      Delhi
3    104    David   28         IT   65000  Bangalore
4    105      Eva   26         HR   55000       Pune

In [3]:
type(df)

pandas.core.frame.DataFrame

In [8]:
df.shape

(5, 6)

In [10]:
df.head(2)

   EmpID   Name  Age Department  Salary    City
0    101  Alice   25         HR   50000    Pune
1    102    Bob   30         IT   70000  Mumbai

In [11]:
df.tail(2)

   EmpID   Name  Age Department  Salary       City
3    104  David   28         IT   65000  Bangalore
4    105    Eva   26         HR   55000       Pune

In [12]:
df.columns

Index(['EmpID', 'Name', 'Age', 'Department', 'Salary', 'City'], dtype='object')

In [13]:
df.columns.tolist()

['EmpID', 'Name', 'Age', 'Department', 'Salary', 'City']

In [15]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   EmpID       5 non-null      int64
 1   Name        5 non-null      object
 2   Age         5 non-null      int64
 3   Department  5 non-null      object
 4   Salary      5 non-null      int64
 5   City        5 non-null      object
dtypes: int64(3), object(3)
memory usage: 372.0+ bytes

In [20]:
df.describe()

            EmpID        Age        Salary
count    5.000000   5.000000      5.000000
mean   103.000000  28.800000  64000.000000
std      1.581139   3.962323  11937.336386
min    101.000000  25.000000  50000.000000
25%    102.000000  26.000000  55000.000000
50%    103.000000  28.000000  65000.000000
75%    104.000000  30.000000  70000.000000
max    105.000000  35.000000  80000.000000

In [24]:
df.describe(include='all')

             EmpID   Name        Age Department        Salary  City
count     5.000000      5   5.000000          5      5.000000     5
unique         NaN      5        NaN          3           NaN     4
top            NaN  Alice        NaN         HR           NaN  Pune
freq           NaN      1        NaN          2           NaN     2
mean    103.000000    NaN  28.800000        NaN  64000.000000   NaN
std       1.581139    NaN   3.962323        NaN  11937.336386   NaN
min     101.000000    NaN  25.000000        NaN  50000.000000   NaN
25%     102.000000    NaN  26.000000        NaN  55000.000000   NaN
50%     103.000000    NaN  28.000000        NaN  65000.000000   NaN
75%     104.000000    NaN  30.000000        NaN  70000.000000   NaN
max     105.000000    NaN  35.000000        NaN  80000.000000   NaN

In [26]:
df['Name']

0      Alice
1        Bob
2    Charlie
3      David
4        Eva
Name: Name, dtype: object

In [29]:
df.columns

Index(['EmpID', 'Name', 'Age', 'Department', 'Salary', 'City'], dtype='object')

In [31]:
df[['Name','Age']]

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   28
4      Eva   26

In [32]:
df.iloc[0]

EmpID           101
Name          Alice
Age              25
Department       HR
Salary        50000
City           Pune
Name: 0, dtype: object

In [34]:
df.iloc[2]

EmpID             103
Name          Charlie
Age                35
Department    Finance
Salary          80000
City            Delhi
Name: 2, dtype: object

In [36]:
df.iloc[0:2]

   EmpID   Name  Age Department  Salary    City
0    101  Alice   25         HR   50000    Pune
1    102    Bob   30         IT   70000  Mumbai

In [37]:
df.loc[0]

EmpID           101
Name          Alice
Age              25
Department       HR
Salary        50000
City           Pune
Name: 0, dtype: object

In [38]:
df.loc[0:2]

   EmpID     Name  Age Department  Salary    City
0    101    Alice   25         HR   50000    Pune
1    102      Bob   30         IT   70000  Mumbai
2    103  Charlie   35    Finance   80000   Delhi

In [41]:
df.loc[0,'Name']

'Alice'

In [39]:
df.iloc[0:2] # slicing end excluded

   EmpID   Name  Age Department  Salary    City
0    101  Alice   25         HR   50000    Pune
1    102    Bob   30         IT   70000  Mumbai

In [42]:
df["Bonus"] = [5000, 7000, 8000, 6500, 5500]
df

   EmpID     Name  Age Department  Salary       City  Bonus
0    101    Alice   25         HR   50000       Pune   5000
1    102      Bob   30         IT   70000     Mumbai   7000
2    103  Charlie   35    Finance   80000      Delhi   8000
3    104    David   28         IT   65000  Bangalore   6500
4    105      Eva   26         HR   55000       Pune   5500

In [43]:
df['totak '] = df['Salary'] + df['Bonus']
df

   EmpID     Name  Age Department  Salary       City  Bonus  totak
0    101    Alice   25         HR   50000       Pune   5000   55000
1    102      Bob   30         IT   70000     Mumbai   7000   77000
2    103  Charlie   35    Finance   80000      Delhi   8000   88000
3    104    David   28         IT   65000  Bangalore   6500   71500
4    105      Eva   26         HR   55000       Pune   5500   60500

In [47]:
df.columns

Index(['EmpID', 'Name', 'Age', 'Department', 'Salary', 'City', 'Bonus',
       'totak '],
      dtype='object')

In [48]:
df['totak']  = df['totak '] + 1000000
df

   EmpID     Name  Age Department  Salary       City  Bonus  totak     totak
0    101    Alice   25         HR   50000       Pune   5000   55000  1055000
1    102      Bob   30         IT   70000     Mumbai   7000   77000  1077000
2    103  Charlie   35    Finance   80000      Delhi   8000   88000  1088000
3    104    David   28         IT   65000  Bangalore   6500   71500  1071500
4    105      Eva   26         HR   55000       Pune   5500   60500  1060500

In [51]:
df.rename(columns={'totak ':'total'},inplace=True)
df.columns

Index(['EmpID', 'Name', 'Age', 'Department', 'Salary', 'City', 'Bonus',
       'total', 'totak'],
      dtype='object')

In [57]:
df

   EmpID     Name  Age     Dept  Salary       City  Bonus  total    totak
0    101    Alice   25       HR   50000       Pune   5000  55000  1055000
1    102      Bob   30       IT   70000     Mumbai   7000  77000  1077000
2    103  Charlie   35  Finance   80000      Delhi   8000  88000  1088000
3    104    David   28       IT   65000  Bangalore   6500  71500  1071500
4    105      Eva   26       HR   55000       Pune   5500  60500  1060500

In [58]:
df.rename(columns={'Dept':'new_dpt'},inplace=True)
df.columns

Index(['EmpID', 'Name', 'Age', 'new_dpt', 'Salary', 'City', 'Bonus', 'total',
       'totak'],
      dtype='object')

In [59]:

df.rename(columns={"Department": "Dept"}, inplace=True)

print("\nRenamed Column")
print(df)

Renamed Column
   EmpID     Name  Age  new_dpt  Salary       City  Bonus  total    totak
0    101    Alice   25       HR   50000       Pune   5000  55000  1055000
1    102      Bob   30       IT   70000     Mumbai   7000  77000  1077000
2    103  Charlie   35  Finance   80000      Delhi   8000  88000  1088000
3    104    David   28       IT   65000  Bangalore   6500  71500  1071500
4    105      Eva   26       HR   55000       Pune   5500  60500  1060500

In [61]:
df.columns

Index(['EmpID', 'Name', 'Age', 'new_dpt', 'Salary', 'City', 'Bonus', 'total',
       'totak'],
      dtype='object')

In [63]:
df.drop('totak',axis=1,inplace=True)
df

   EmpID     Name  Age  new_dpt  Salary       City  Bonus  total
0    101    Alice   25       HR   50000       Pune   5000  55000
1    102      Bob   30       IT   70000     Mumbai   7000  77000
2    103  Charlie   35  Finance   80000      Delhi   8000  88000
3    104    David   28       IT   65000  Bangalore   6500  71500
4    105      Eva   26       HR   55000       Pune   5500  60500

In [64]:
d = df.copy()
d

   EmpID     Name  Age  new_dpt  Salary       City  Bonus  total
0    101    Alice   25       HR   50000       Pune   5000  55000
1    102      Bob   30       IT   70000     Mumbai   7000  77000
2    103  Charlie   35  Finance   80000      Delhi   8000  88000
3    104    David   28       IT   65000  Bangalore   6500  71500
4    105      Eva   26       HR   55000       Pune   5500  60500

In [65]:
del d
d

NameError: name 'd' is not defined

In [69]:
#  --------------------------------------------------------

df3 = df.copy()

removed = df3.pop("City")

print("\nAfter Pop")
print(df3)

print("\nRemoved Column")
print(removed)

After Pop
   EmpID     Name  Age  new_dpt  Salary  Bonus  total
0    101    Alice   25       HR   50000   5000  55000
1    102      Bob   30       IT   70000   7000  77000
2    103  Charlie   35  Finance   80000   8000  88000
3    104    David   28       IT   65000   6500  71500
4    105      Eva   26       HR   55000   5500  60500

Removed Column
0         Pune
1       Mumbai
2        Delhi
3    Bangalore
4         Pune
Name: City, dtype: object

In [73]:
# -----------------------------------------------------------

df4 = df.copy()

df4.index = [11, 12, 13, 14, 15]

print("\nChanged Index")
print(df4)

Changed Index
    EmpID     Name  Age  new_dpt  Salary       City  Bonus  total
11    101    Alice   25       HR   50000       Pune   5000  55000
12    102      Bob   30       IT   70000     Mumbai   7000  77000
13    103  Charlie   35  Finance   80000      Delhi   8000  88000
14    104    David   28       IT   65000  Bangalore   6500  71500
15    105      Eva   26       HR   55000       Pune   5500  60500

In [74]:
df4.reset_index(inplace=True)
 
df4

   index  EmpID     Name  Age  new_dpt  Salary       City  Bonus  total
0     11    101    Alice   25       HR   50000       Pune   5000  55000
1     12    102      Bob   30       IT   70000     Mumbai   7000  77000
2     13    103  Charlie   35  Finance   80000      Delhi   8000  88000
3     14    104    David   28       IT   65000  Bangalore   6500  71500
4     15    105      Eva   26       HR   55000       Pune   5500  60500

In [75]:
df.columns

Index(['EmpID', 'Name', 'Age', 'new_dpt', 'Salary', 'City', 'Bonus', 'total'], dtype='object')

In [76]:
df[['EmpID', 'Name', 'Age']]

   EmpID     Name  Age
0    101    Alice   25
1    102      Bob   30
2    103  Charlie   35
3    104    David   28
4    105      Eva   26

In [80]:
df['Name'].value_counts()

Alice      1
Bob        1
Charlie    1
David      1
Eva        1
Name: Name, dtype: int64

In [84]:
# list(df['Name'].unique())
(df['Name'].unique()).tolist()

['Alice', 'Bob', 'Charlie', 'David', 'Eva']

In [85]:
df['Salary'].max()

80000

In [86]:
import pandas as pd
from ydata_profiling import ProfileReport
profile = ProfileReport(df)
profile.to_file("report.html")

ModuleNotFoundError: No module named 'ydata_profiling'

In [88]:
df.sort_values('Salary',ascending=True)
df.sort_values('Salary')
df.sort_values('Salary')

   EmpID     Name  Age  new_dpt  Salary       City  Bonus  total
0    101    Alice   25       HR   50000       Pune   5000  55000
4    105      Eva   26       HR   55000       Pune   5500  60500
3    104    David   28       IT   65000  Bangalore   6500  71500
1    102      Bob   30       IT   70000     Mumbai   7000  77000
2    103  Charlie   35  Finance   80000      Delhi   8000  88000

In [ ]:
pd.to_csv('emp.csv',index=False)

In [92]:
d = df[df['Age']>30]
d

   EmpID     Name  Age  new_dpt  Salary   City  Bonus  total
2    103  Charlie   35  Finance   80000  Delhi   8000  88000

In [100]:
d = df[(df['Age']>30) & (df['Salary']>=80000)]
d = df[(df['Age']>30)&(df['Salary']>=80000)]
d

   EmpID     Name  Age  new_dpt  Salary   City  Bonus  total
2    103  Charlie   35  Finance   80000  Delhi   8000  88000

In [101]:
df[df['Age'].isin([30,35])]

   EmpID     Name  Age  new_dpt  Salary    City  Bonus  total
1    102      Bob   30       IT   70000  Mumbai   7000  77000
2    103  Charlie   35  Finance   80000   Delhi   8000  88000

In [102]:
df[df['Age'].between(28,38)]

   EmpID     Name  Age  new_dpt  Salary       City  Bonus  total
1    102      Bob   30       IT   70000     Mumbai   7000  77000
2    103  Charlie   35  Finance   80000      Delhi   8000  88000
3    104    David   28       IT   65000  Bangalore   6500  71500

In [104]:
df.query("Age > 30")

   EmpID     Name  Age  new_dpt  Salary   City  Bonus  total
2    103  Charlie   35  Finance   80000  Delhi   8000  88000

In [105]:
df.isnull()

   EmpID   Name    Age  new_dpt  Salary   City  Bonus  total
0  False  False  False    False   False  False  False  False
1  False  False  False    False   False  False  False  False
2  False  False  False    False   False  False  False  False
3  False  False  False    False   False  False  False  False
4  False  False  False    False   False  False  False  False

In [106]:
df.isnull().sum()

EmpID      0
Name       0
Age        0
new_dpt    0
Salary     0
City       0
Bonus      0
total      0
dtype: int64

In [113]:
df.fillna(0)

   EmpID     Name  Age  new_dpt   Salary       City  Bonus  total
0    101    Alice   25       HR  50000.0       Pune   5000  55000
1    102      Bob   30       IT  70000.0     Mumbai   7000  77000
2    103  Charlie   35  Finance      0.0      Delhi   8000  88000
3    104    David   28       IT  65000.0  Bangalore   6500  71500
4    105      Eva   26       HR  55000.0       Pune   5500  60500

In [114]:
import numpy as np
df.loc[2, "Salary"] = np.nan
df

   EmpID     Name  Age  new_dpt   Salary       City  Bonus  total
0    101    Alice   25       HR  50000.0       Pune   5000  55000
1    102      Bob   30       IT  70000.0     Mumbai   7000  77000
2    103  Charlie   35  Finance      NaN      Delhi   8000  88000
3    104    David   28       IT  65000.0  Bangalore   6500  71500
4    105      Eva   26       HR  55000.0       Pune   5500  60500

In [117]:
df = df.fillna(0)
df

   EmpID     Name  Age  new_dpt   Salary       City  Bonus  total
0    101    Alice   25       HR  50000.0       Pune   5000  55000
1    102      Bob   30       IT  70000.0     Mumbai   7000  77000
2    103  Charlie   35  Finance      0.0      Delhi   8000  88000
3    104    David   28       IT  65000.0  Bangalore   6500  71500
4    105      Eva   26       HR  55000.0       Pune   5500  60500

In [118]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [119]:
df.duplicated().sum()

0

In [120]:
df.drop_duplicates()

   EmpID     Name  Age  new_dpt   Salary       City  Bonus  total
0    101    Alice   25       HR  50000.0       Pune   5000  55000
1    102      Bob   30       IT  70000.0     Mumbai   7000  77000
2    103  Charlie   35  Finance      0.0      Delhi   8000  88000
3    104    David   28       IT  65000.0  Bangalore   6500  71500
4    105      Eva   26       HR  55000.0       Pune   5500  60500

In [122]:
df['Name'].str.lower()

0      alice
1        bob
2    charlie
3      david
4        eva
Name: Name, dtype: object

In [123]:
df['Name'].apply(len)

0    5
1    3
2    7
3    5
4    3
Name: Name, dtype: int64

In [127]:
df['Age'].apply(int)

0    25
1    30
2    35
3    28
4    26
Name: Age, dtype: int64

In [129]:
df.columns

Index(['EmpID', 'Name', 'Age', 'new_dpt', 'Salary', 'City', 'Bonus', 'total'], dtype='object')

In [130]:
df

   EmpID     Name  Age  new_dpt   Salary       City  Bonus  total
0    101    Alice   25       HR  50000.0       Pune   5000  55000
1    102      Bob   30       IT  70000.0     Mumbai   7000  77000
2    103  Charlie   35  Finance      0.0      Delhi   8000  88000
3    104    David   28       IT  65000.0  Bangalore   6500  71500
4    105      Eva   26       HR  55000.0       Pune   5500  60500

In [133]:
df["EmpID"].apply(lambda x: x + 1000)
df

   EmpID     Name  Age  new_dpt   Salary       City  Bonus  total
0    101    Alice   25       HR  50000.0       Pune   5000  55000
1    102      Bob   30       IT  70000.0     Mumbai   7000  77000
2    103  Charlie   35  Finance      0.0      Delhi   8000  88000
3    104    David   28       IT  65000.0  Bangalore   6500  71500
4    105      Eva   26       HR  55000.0       Pune   5500  60500

In [134]:
gender = {
    "Alice": "Female",
    "Bob": "Male",
    "Charlie": "Male"
}
df['Gender'] = df['Name'].map(gender)

df["Gender"] = df["Name"].map(gender)
df

   EmpID     Name  Age  new_dpt   Salary       City  Bonus  total  Gender
0    101    Alice   25       HR  50000.0       Pune   5000  55000  Female
1    102      Bob   30       IT  70000.0     Mumbai   7000  77000    Male
2    103  Charlie   35  Finance      0.0      Delhi   8000  88000    Male
3    104    David   28       IT  65000.0  Bangalore   6500  71500     NaN
4    105      Eva   26       HR  55000.0       Pune   5500  60500     NaN

In [136]:
df.replace("HR", "Human Resource")  # wholde df
df.replace("Human Resource",'HRRRRRRRRRR')

   EmpID     Name  Age  new_dpt   Salary       City  Bonus  total  Gender
0    101    Alice   25       HR  50000.0       Pune   5000  55000  Female
1    102      Bob   30       IT  70000.0     Mumbai   7000  77000    Male
2    103  Charlie   35  Finance      0.0      Delhi   8000  88000    Male
3    104    David   28       IT  65000.0  Bangalore   6500  71500     NaN
4    105      Eva   26       HR  55000.0       Pune   5500  60500     NaN

In [138]:
df.replace("Pune",'HRRRRRRRRRR')

   EmpID     Name  Age  new_dpt   Salary         City  Bonus  total  Gender
0    101    Alice   25       HR  50000.0  HRRRRRRRRRR   5000  55000  Female
1    102      Bob   30       IT  70000.0       Mumbai   7000  77000    Male
2    103  Charlie   35  Finance      0.0        Delhi   8000  88000    Male
3    104    David   28       IT  65000.0    Bangalore   6500  71500     NaN
4    105      Eva   26       HR  55000.0  HRRRRRRRRRR   5500  60500     NaN

In [139]:
df.sample(3)

df.sample(frac=0.5)
df

   EmpID     Name  Age  new_dpt   Salary       City  Bonus  total  Gender
0    101    Alice   25       HR  50000.0       Pune   5000  55000  Female
1    102      Bob   30       IT  70000.0     Mumbai   7000  77000    Male
2    103  Charlie   35  Finance      0.0      Delhi   8000  88000    Male
3    104    David   28       IT  65000.0  Bangalore   6500  71500     NaN
4    105      Eva   26       HR  55000.0       Pune   5500  60500     NaN

In [2]:
import pandas as pd
import numpy as np

data = {
    "Emp_ID":[101,102,103,104,105,106],
    "Name":["Alice","Bob","Charlie","David","Eva","Frank"],
    "Department":["IT","HR","IT","Finance","HR","IT"],
    "Salary":[60000,45000,70000,50000,48000,80000],
    "Age":[25,30,35,40,29,32],
    "City":["Pune","Mumbai","Pune","Delhi","Mumbai","Pune"]
}

df = pd.DataFrame(data)

df

   Emp_ID     Name Department  Salary  Age    City
0     101    Alice         IT   60000   25    Pune
1     102      Bob         HR   45000   30  Mumbai
2     103  Charlie         IT   70000   35    Pune
3     104    David    Finance   50000   40   Delhi
4     105      Eva         HR   48000   29  Mumbai
5     106    Frank         IT   80000   32    Pune

In [4]:
df['Salary'].min()

45000

In [5]:
df['Salary'].median()

55000.0

In [6]:
df['Salary'].count()

6

In [7]:
df['Salary'].std()

13862.419221285534

In [9]:
df.columns

Index(['Emp_ID', 'Name', 'Department', 'Salary', 'Age', 'City'], dtype='object')

In [11]:
group = df.groupby('Department')
print(group)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x00000286959C7F90>

In [12]:
group = df.groupby('Department')
group.count()

            Emp_ID  Name  Salary  Age  City
Department
Finance          1     1       1    1     1
HR               2     2       2    2     2
IT               3     3       3    3     3

In [14]:
group = df.groupby('Department')['Salary'].sum()
group

Department
Finance     50000
HR          93000
IT         210000
Name: Salary, dtype: int64

In [15]:
df.groupby("Department")["Salary"].mean()

Department
Finance    50000.0
HR         46500.0
IT         70000.0
Name: Salary, dtype: float64

In [19]:
df.groupby("Department")["Salary"].agg(["sum","mean","max","min","count"])
df.groupby('Department')['Salary'].agg(['sum','min','max'])

               sum    min    max
Department
Finance      50000  50000  50000
HR           93000  45000  48000
IT          210000  60000  80000

In [22]:
result = df.groupby("Department")["Salary"].min()

print(result)
result['HR']

Department
Finance    50000
HR         45000
IT         60000
Name: Salary, dtype: int64

45000

In [26]:
group = df.groupby(['Department','City'])['Salary']
group.sum()

Department  City
Finance     Delhi      50000
HR          Mumbai     93000
IT          Pune      210000
Name: Salary, dtype: int64

In [29]:
group = df.groupby('Department')['Salary']
group.get_group('IT')

0    60000
2    70000
5    80000
Name: Salary, dtype: int64

In [30]:
df.groupby("Department").size()

Department
Finance    1
HR         2
IT         3
dtype: int64

In [31]:
df[df["Department"] == "HR"]["Salary"]

1    45000
4    48000
Name: Salary, dtype: int64

In [32]:
df

   Emp_ID     Name Department  Salary  Age    City
0     101    Alice         IT   60000   25    Pune
1     102      Bob         HR   45000   30  Mumbai
2     103  Charlie         IT   70000   35    Pune
3     104    David    Finance   50000   40   Delhi
4     105      Eva         HR   48000   29  Mumbai
5     106    Frank         IT   80000   32    Pune

In [ ]:
df1,df2
df.join(df2,on=['Dpt'])
df = pd.merge(df1,df2,on=['DRP00'],how = 'inner')

In [1]:
import random

lst = [random.randint(0, 1) for _ in range(50)]

print(lst)

import random
lst = [random.randint(0,1) for i in range(20)]
lst

[0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0]

[1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0]

In [4]:
lst = [random.randint(0,100) for i in range(10)]
lst

[78, 64, 76, 57, 7, 21, 76, 64, 93, 26]

In [13]:
#  Find the IDs of products that are both low-fat (low_fats == 'Y') and recyclable (recyclable == 'Y').

import pandas as pd

# Sample DataFrame
products = pd.DataFrame({
    'product_id': [1, 2, 3, 4],
    'low_fats': ['Y', 'N', 'Y', 'Y'],
    'recyclable': ['N', 'Y', 'Y', 'Y']
})

condiction =(products['low_fats']=='Y') &(products['recyclable']=='Y')
res = products[condiction][['product_id']]
res
# Code Solution
# condition = (products['low_fats'] == 'Y') & (products['recyclable'] == 'Y')
# result = products[condition][['product_id']]
# print(result)

   product_id
2           3
3           4

In [22]:
#  Given an orders dataset, calculate the total revenue generated per product category and sort it in descending order.

orders = pd.DataFrame({
    'category': ['Electronics', 'Clothing', 'Electronics', 'Clothing', 'Home'],
    'total_price': [500, 40, 1200, 80, 150]
})

group = orders.groupby(['category'])['total_price'].sum().reset_index().sort_values(by='total_price',ascending = True)
group

      category  total_price
0     Clothing          120
2         Home          150
1  Electronics         1700

      category  total_price
0     Clothing          120
2         Home          150
1  Electronics         1700

In [27]:
#  Compare each employee's salary with the average salary of their corresponding department. The output must contain an additional column for the department's average

employees = pd.DataFrame({
    'first_name': ['Alice', 'Bob', 'Charlie', 'David'],
    'department': ['HR', 'IT', 'IT', 'HR'],
    'salary': [50000, 80000, 110000, 60000]
})

# Code Solution
employees['dept_avg_salary'] = employees.groupby('department')['salary'].transform('mean')
print(employees)

  first_name department  salary  dept_avg_salary
0      Alice         HR   50000          55000.0
1        Bob         IT   80000          95000.0
2    Charlie         IT  110000          95000.0
3      David         HR   60000          55000.0
  first_name department  salary  dept_avg_salary
0      Alice         HR   50000          55000.0
1        Bob         IT   80000          95000.0
2    Charlie         IT  110000          95000.0
3      David         HR   60000          55000.0

In [1]:
import pandas as pd

df = pd.DataFrame({
    "salary": [30000, 60000, 45000, 80000]
})

print(df)

   salary
0   30000
1   60000
2   45000
3   80000

In [2]:
df["flag"] = df["salary"].apply(
    lambda x: 1 if x > 50000 else 0
)

In [3]:
def check_salary(x):
    if x > 50000:
        return 1
    else:
        return 0

df["flag"] = df["salary"].apply(check_salary)

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "A": [1,2],
    "B": [3,4]
})

def total(row):
    return row["A"] + row["B"]

df["Total"] = df.apply(total, axis=1)

print(df)